### ISSUE TITLE
 add support  format YOLOv5

### ISSUE THREAD

**Issue by husia777** [cvat-ai/datumaro#33]
hi, how to add export support to YOLOv5 format, I know how to do it in openvinotoolkit/datumaro, but it turns out you have a different version, please help

**Comment by zhiltsov-max** [comment]
Hi. I don't think we're going to implement it in the fork. If you need the format, please consider exporting in any compatible format (e.g. Datumaro, COCO), and then convert into the needed format using an existing script or the upstream Datumaro.
